title: Visualizing Plane Crashes
description: 
  Visualizing Letal Plane Crashes with d3v4
baseurl: "story.html"
url: "https://sschneaky.github.io" 
github_username:  sschneaky

# Build settings
markdown: kramdown